package com.jspiders.cardekho_case_study_MVC.Pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class CarAdminPojo {
	@Id //id field is marked as the primary key, and its values will be automatically generated by the database..
	@GeneratedValue(strategy = GenerationType.IDENTITY)  // which is assign automatically genrated primary value for each new record.
	
	private int id;
	private String username;
	private String password;
	
	
	public void setPassword(String password) {
		this.password = password;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	

}
